name: Run latex resume builder script

on:
  push:
    branches:
      - main

jobs:
  make_resume:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve code
        uses: actions/checkout@v3

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Build docker image
        run: just build

      - name: Make pdf
        run: just run

      - name: Upload the pdf
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: data/resume.pdf
